feat: login출력
Doong-Ji/nestalk-frontend pull request #26
Opened 2021-03-14 11:19 UTC by sophia-jeong

# 제목
feat: login출력

## 해당 이슈 📎

#15 

## 변경 사항 🛠

구현내용 요약

- login html

## 테스트 ✨

없음

## 리뷰어 참고 사항 🙋‍♀️

자동로그인은 구현하지 않았습니다.

2021-03-21 11:01 UTC, EUN-HYE-KIM requested changes
head 부분 공통으로 맞춰주세요~ :)

2021-03-21 13:19 UTC, mood-mood approved these changes
단어들 수정 부탁드려요!

2021-03-21 13:19 UTC, mood-mood commented on public/login-page/login.html
> +    <title>document</title>
title 변경 부탁드려요!

2021-03-21 13:19 UTC, mood-mood commented on public/login-page/login.html
> +          <div class="btn-area">
btn는 저희끼리 사용하는 약어이므로 button으로 수정해주시면 좋을꺼같아요!ㅎㅎ

2021-04-03 13:51 UTC, soyoung-k commented on public/login-page/login.html
> +          <div class="btn-area">
안녕하세요~! 프론트엔드 개발하고 있는 김소영이라고 합니다:)
우연히 마크업 리뷰보다가 궁금한 점이 생겨 질문 남깁니다.
btn(button)의 경우 무분별한 약어가 아닌 많이 사용되고 있는 약어인거 같은데 지양하시는 이유가 있으실까요?
단순한 궁금증입니다!!:)

2021-04-04 06:39 UTC, EUN-HYE-KIM commented on public/login-page/login.html
> +          <div class="btn-area">
안녕하세요 소영님 퍼블리싱 파트장을 맡고 있는 김은혜입니다 ;)

말씀주신대로 btn은 많이 통용되는 약어가 맞습니다. 저희도 실제로 btn을 많이 사용하기도 하구요
다만 모두가 알아 볼 수 있게 약어을 지양하고 풀어쓰자는 취지에 맞춰서 하다 보니 기준이 모호하여 전부다 풀어쓰게 되었습니다 ㅎ

약어는 서로간에 약속만 되어 있고 알아 볼 수만 있다면 사용해도 될 것으로 보이는데 다음 프로젝트에서는 이런 부분들을 정리하고 가면 좋을 것 같네요 ㅎ 궁금증이 해소 되셨을지 모르겠네요 ^-^

2021-04-04 13:25 UTC, soyoung-k commented on public/login-page/login.html
> +          <div class="btn-area">
아하 그렇군요!!!
약어같은 경우도 쓸거 안쓸거 정리해서 컨벤션을 만드는군요! 도움됐습니다 답변 감사합니다!!!😊

2021-04-07 13:36 UTC, EUN-HYE-KIM commented
담당자 변경으로 PR을 닫습니다.

2021-04-07 13:36 UTC, closed without merging