Feature/add image icon
Doong-Ji/nestalk-frontend pull request #43
Opened 2021-03-24 15:59 UTC by EUN-HYE-KIM

# Feature/add image icon

## 해당 이슈 📎
없음

## 변경 사항 🛠
아이콘 변경 및 추가

구현내용 요약

- 연락처
- ID
- 배경화면
- 친구추가
- 기본 프로필
- 친구

## 테스트 ✨

없음

## 리뷰어 참고 사항 🙋‍♀️
- 기본 프로필의 아이콘이 동일하지 않아 변경
- 그 외 추가로 필요한 아이콘들 올립니다.

2021-03-24 16:00 UTC, chloenam approved these changes
추가하신 icon 확인 완료요!

2021-03-25 00:31 UTC, HwanChang approved these changes

2021-03-25 00:32 UTC, HwanChang requested changes
conflict 만 해결해주시면 될 것 같습니다.

2021-03-25 14:33 UTC, HwanChang approved these changes

2021-03-25 15:12 UTC, merged